services:
  - type: web
    name: bp-calculator-qa
    env: docker
    region: frankfurt # Closest region to Ireland
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
